// Mocks generated by Mockito 5.4.4 from annotations
// in temp_donor/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i10;
import 'dart:typed_data' as _i12;

import 'package:dartz/dartz.dart' as _i2;
import 'package:error/error.dart' as _i7;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:temp_donor/src/data/data_sources/temp_donor_remote_data_source.dart'
    as _i8;
import 'package:temp_donor/src/domain/entities/TempDonor.dart' as _i3;
import 'package:temp_donor/src/domain/repository/temp_donor_repository.dart'
    as _i4;
import 'package:temp_donor/src/domain/usecases/add_temp_donor_usecase.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTempDonor_1 extends _i1.SmartFake implements _i3.TempDonor {
  _FakeTempDonor_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTempDonorRepository_2 extends _i1.SmartFake
    implements _i4.TempDonorRepository {
  _FakeTempDonorRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TempDonorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTempDonorRepository extends _i1.Mock
    implements _i4.TempDonorRepository {
  MockTempDonorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i3.TempDonor>> addTempDonor(
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? mobile,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTempDonor,
          [
            firstName,
            lastName,
            email,
            password,
            mobile,
          ],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i3.TempDonor>>.value(
            _FakeEither_0<_i7.Failure, _i3.TempDonor>(
          this,
          Invocation.method(
            #addTempDonor,
            [
              firstName,
              lastName,
              email,
              password,
              mobile,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i3.TempDonor>>);
}

/// A class which mocks [TempDonorRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTempDonorRemoteDataSource extends _i1.Mock
    implements _i8.TempDonorRemoteDataSource {
  MockTempDonorRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.TempDonor> addTempDonor(
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? mobile,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTempDonor,
          [
            firstName,
            lastName,
            email,
            password,
            mobile,
          ],
        ),
        returnValue: _i6.Future<_i3.TempDonor>.value(_FakeTempDonor_1(
          this,
          Invocation.method(
            #addTempDonor,
            [
              firstName,
              lastName,
              email,
              password,
              mobile,
            ],
          ),
        )),
      ) as _i6.Future<_i3.TempDonor>);
}

/// A class which mocks [AddTempDonorUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTempDonorUsecase extends _i1.Mock
    implements _i9.AddTempDonorUsecase {
  MockAddTempDonorUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TempDonorRepository get tempDonorRepository => (super.noSuchMethod(
        Invocation.getter(#tempDonorRepository),
        returnValue: _FakeTempDonorRepository_2(
          this,
          Invocation.getter(#tempDonorRepository),
        ),
      ) as _i4.TempDonorRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i3.TempDonor>> execute(
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? mobile,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            firstName,
            lastName,
            email,
            password,
            mobile,
          ],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i3.TempDonor>>.value(
            _FakeEither_0<_i7.Failure, _i3.TempDonor>(
          this,
          Invocation.method(
            #execute,
            [
              firstName,
              lastName,
              email,
              password,
              mobile,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i3.TempDonor>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i5.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i12.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
      ) as _i6.Future<_i12.Uint8List>);

  @override
  _i6.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i6.Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i6.Future<_i5.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
